version: '3.8'
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/mysql

  web:
    depends_on:
      - db
    build: ./
    ports:
      - 3000:3000
    environment:
      - .env

volumes: 
  db:
